### ISSUE TITLE
Add Gimci.js which will help query auto suggestions and many more

### ISSUE THREAD

**Issue by gimochi** [tymsai/marmoym-api#27]

**Comment by gimochi** [comment]
convertRomanToHangyr('안녕') -> 'Annieng' 
=>  convertHangyrToRoman('안녕') -> 'Annieng'

convertHangyrToRoman('Annieng') -> '안녕'
=> convertRomanToHangyr('Annieng') -> '안녕'

**Comment by enginehenryed** [comment]
this should be accompanied with the modification of Gimci as well

**Comment by enginehenryed** [comment]
this should be accompanied with the modification of Gimci as well
