### ISSUE TITLE
VSCode settings.json, keybindings.json, snippets/ to be version controlled

### ISSUE THREAD

**Issue by enginehenryed** [tymsai/marmoym-api#46]

**Comment by jcooky** [comment]
VSCode의 설정 파일은 CONTRIBUTING.md를 통해 다운로드할 수 있도록 하면 좋을 것 같습니다.

**Comment by enginehenryed** [comment]
@jcooky Sure. Keeping those files in [marmoym](https://github.com/tymsai/marmoym) and noting it on CONTRIBUTING.md would be nice. This way, a number of projects that are developed with VSCode can get help

**Comment by enginehenryed** [comment]
Done by https://github.com/tymsai/marmoym-dev-support/commit/6a6030673f525ca9742b09f075f8d1590adcf93d
