### ISSUE TITLE
User functionalities - SignIn and token generating/validating to be fixed

### ISSUE THREAD

**Issue by enginehenryed** [tymsai/marmoym-api#48]
@jcooky will handle this

**Comment by jcooky** [comment]
Express에서 session을 쿠키로 처리하고 있다. 이는 싱글 어플리케이션일 경우 원활히 동작하며 가장 기본적인 동작입니다.
하지만, 저는 scale out을 위해 [connect-redis](https://github.com/tj/connect-redis)와 express-session을 이용한 session 처리를 하며 이에 user의 정보를 저장하는 것을 제안합니다.

**Comment by enginehenryed** [comment]
현재 서버로부터 session을 사용하지 않는 방식을 채택하고 있는데요, 하시는 말씀의 session이 그것이 아닌 것이지요? token을 redis에 저장하겠다는 것말고 또 다른 고려 사항이 있을까요?

**Comment by jcooky** [comment]
음.. token으로 현재 유지할려면 각 유저마다 private key를 생성하여 갖고 있어야 합니다. 이 부분은 SSL의 키를 가져오는 것이 일반적이지요. Redis와 session을 사용하게 되면 이러한 부분들이 SSL Cert를 이용하여 middleware에서 어느정도 자동으로 처리해주리라 기대하기 때문에 제안하는 것입니다.

**Comment by enginehenryed** [comment]
그럼 token구조 개선하면서 ssl을 아예 달아버리는 것도 좋겠군요. 일단 issue는 하나 생성할게요. 지금 [vultr](https://www.vultr.com/) 이용하고 있는데, 가지고 있는 vm장비에 ssl 설치해야겠습니다. 최근엔 비용도 들지 않더군요.

**Comment by gimochi** [comment]
Done by #47
