### ISSUE TITLE
ORM or QueryBuilder to reconsider due to a incongruence with TypeScrtipt. Knex is a candidate

### ISSUE THREAD

**Issue by enginehenryed** [tymsai/marmoym-api#89]
https://npmcompare.com/compare/bookshelf,knex,objection,orm,sequelize
https://www.reddit.com/r/node/comments/5p9y0l/orm_for_node_which_is_better_bookshelf_or/

**Comment by enginehenryed** [comment]
Even with hapi.js
https://scotch.io/tutorials/making-a-restful-api-with-hapi-js

**Comment by gimochi** [comment]
This issue is fixed in branch `dev`
