### ISSUE TITLE
Express parameter validation

### ISSUE THREAD

**Issue by enginehenryed** [tymsai/marmoym-api#94]

**Comment by gimochi** [comment]
https://github.com/ctavan/express-validator

**Comment by enginehenryed** [comment]
Quite heavy for our case, I guess?

**Comment by enginehenryed** [comment]
Draft taken in charge

**Comment by enginehenryed** [comment]
A lots of thoughts going on here. Finally brining to an end.

- validation will be declared all at once in one place of the codebase, in the form of a router middleware, before url handlers.
- plain js object will be used to handle all the various combination of `url` + `method`.

**Comment by enginehenryed** [comment]
Done by #168
